PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX go: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX bl: <https://w3id.org/biolink/vocab/>
PREFIX MONDO: <http://purl.obolibrary.org/obo/MONDO_>
PREFIX SO: <http://purl.obolibrary.org/obo/SO_>
PREFIX RO: <http://purl.obolibrary.org/obo/RO_>
PREFIX GO: <http://purl.obolibrary.org/obo/GO_>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX NCBIGENE: <http://identifiers.org/ncbigene:>
PREFIX sesame: <http://www.openrdf.org/schema/sesame#>
PREFIX swrl: <http://www.w3.org/2003/11/swrl#>
PREFIX linkml: <https://w3id.org/linkml/>
CONSTRUCT {
  <urn:swrl#x> rdf:type swrl:Variable .
  ?u rdf:type owl:Class .
  [
      rdf:type <http://www.w3.org/2003/11/swrl#Imp> ;
      swrl:body [ 
        rdf:type swrl:AtomList ;
        rdf:first [ 
          rdf:type swrl:ClassAtom ;
          swrl:classPredicate ?r ;
          swrl:argument1 <urn:swrl#x>
        ] ;
        rdf:rest rdf:nil
      ] ;
      swrl:head [ 
        rdf:type swrl:AtomList ;
        rdf:first [ 
          rdf:type swrl:ClassAtom ;
          swrl:classPredicate ?u ;
          swrl:argument1 <urn:swrl#x>
        ] ;
        rdf:rest rdf:nil
      ] 
  ]
}
WHERE {
?r <http://geneontology.org/lego/canonical_record> ?u .
FILTER (isIRI(?u))
}
