PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX InformationBiomacromolecule: <http://purl.obolibrary.org/obo/CHEBI_33695>

CONSTRUCT {
?term rdfs:subClassOf InformationBiomacromolecule: .
}
WHERE {
?s rdf:type ?term .
FILTER (STRSTARTS(STR(?term), "http://identifiers.org/ncbigene"))
FILTER (isIRI(?term))
}
