PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX Gene: <http://purl.obolibrary.org/obo/SO_0000704>

CONSTRUCT {
?term rdfs:subClassOf Gene: .
}
WHERE {
?s ?p ?term .
FILTER (STRSTARTS(STR(?term), "http://identifiers.org/ncbigene"))
FILTER (isIRI(?term))
}
