PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX linkml: <https://w3id.org/linkml/>

SELECT DISTINCT ?bl_subject ?biolink_slot ?bl_object
WHERE {
?s ?p ?o .

?s rdf:type ?bl_subject .
?bl_subject rdf:type linkml:ClassDefinition .

?o rdf:type ?bl_object .
?bl_object rdf:type linkml:ClassDefinition .

?p <http://cam.renci.org/biolink_slot> ?biolink_slot
}
