PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX bl: <https://w3id.org/biolink/vocab/>
PREFIX sesame: <http://www.openrdf.org/schema/sesame#>
PREFIX linkml: <https://w3id.org/linkml/>
SELECT DISTINCT ?p ?p_label
WHERE { 
?n0 rdf:type owl:NamedIndividual .
?n1 rdf:type owl:NamedIndividual .
# For a relation ?p between two individuals
?n0 ?p ?n1 .
OPTIONAL { ?p rdfs:label ?p_label . }
FILTER NOT EXISTS {
  ?p rdfs:subPropertyOf*/<http://cam.renci.org/biolink_slot> ?bl_predicate .
}
}
