PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX blml: <https://w3id.org/biolink/biolinkml/meta/>
PREFIX bl: <https://w3id.org/biolink/vocab/>
PREFIX sesame: <http://www.openrdf.org/schema/sesame#>
PREFIX metatype: <https://w3id.org/biolink/biolinkml/meta/types/>
SELECT DISTINCT ?p ?p_label
WHERE { 
?n0 rdf:type owl:NamedIndividual .
?n1 rdf:type owl:NamedIndividual .
?n0 ?p ?n1 .
?p rdfs:label ?p_label
FILTER NOT EXISTS {
	?p rdfs:subPropertyOf+ ?bl_predicate .
    ?bl_predicate rdf:type metatype:SlotDefinition .
  }
FILTER NOT EXISTS {
    ?p rdf:type metatype:SlotDefinition .
  } 
FILTER NOT EXISTS {
    ?n0 ?p2 ?n1 .
    ?p2 rdfs:subPropertyOf+ ?p .
    FILTER (?p != ?p2)
  }  
}