PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX blml: <https://w3id.org/biolink/biolinkml/meta/>
PREFIX bl: <https://w3id.org/biolink/vocab/>
PREFIX sesame: <http://www.openrdf.org/schema/sesame#>
PREFIX metatype: <https://w3id.org/biolink/biolinkml/meta/types/>
SELECT DISTINCT ?p ?p_label
WHERE { 
?n0 rdf:type owl:NamedIndividual .
?n1 rdf:type owl:NamedIndividual .
# For a relation ?p between two individuals
?n0 ?p ?n1 .
OPTIONAL { ?p rdfs:label ?p_label . }
# There must exist some relation between those individuals which maps to biolink
?n0 ?p1 ?n1 .
FILTER NOT EXISTS {
  ?p1 rdfs:subPropertyOf*/<http://cam.renci.org/biolink_slot> ?bl_predicate .
}
}
