apiVersion: batch/v1
kind: CronJob
metadata:
  name: build-cam-database
  labels:
    project: CAM-KP
    env: dev
spec:
  schedule: "@weekly"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pipeline-tools
            image: "renciorg/cam-pipeline-tools:dev"
            resources:
              limits:
                cpu: '8'
                memory: 150G
            command: ["sh", "-c", "cd /workspace; rm -rf current; mkdir current; cd current; git clone https://github.com/NCATS-Tangerine/cam-pipeline.git; cd cam-pipeline; git checkout add-kubernetes; make all; rm -rf /workspace/success; mv /workspace/current /workspace/success"]
            volumeMounts:
            - mountPath: "/workspace"
              name: storage
          restartPolicy: Never
          volumes:
          - name: storage
            persistentVolumeClaim:
              claimName: build-cam-database-storage
      backoffLimit: 0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-cam-database-storage
  labels:
    project: CAM-KP
    env: dev
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1000G
  storageClassName: basic
